id: P3EACA3C5
initial_creation_type: input
source_metadata:
  title: Drikung Kyobpa Jikten Sumgön
  language: de
  description: 'Texts by and about Drikung Kyobpa Jikten Sumgön (''bri gung skyob
    pa ''jig rten gsum mgon, 1143–1217), founder of the Drikung Kagyü tradition:'
  volume:
    d14c462572694130b200fcaa7511f6a8:
      title: In Praise of Padmākara, the Great Guru of Uḍḍiyāna
      parent: Praise
    ed3571e1e2da4573ba3a65288b177898:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      parent: Praise
    37bc5bc456364afdb964822c0d72acd0:
      title: Verses in Praise of the Protector Akṣobhya
      parent: Praise
    4cf1c1a8755e4f33bb4999b193e36cab:
      title: 'Prayer to Tārā: A Sevenfold Supplication for Protection'
      parent: Prayers
created_at: '2022-02-28T23:03:51.358104'
last_modified_at: '2022-02-28T23:03:51.358108'
